import { StyleSheet } from "react-native";

export default StyleSheet.create({
  card: {
    backgroundColor: '#e8caad',
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
    marginBottom: 15,
    flex: 1,
    marginHorizontal: 5,
  },
  cardImage: {
    width: 110,
    height: 160,
    borderRadius: 10,
    marginBottom: 8,
    resizeMode: 'cover',
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#331307',
    textAlign: 'center',
  },
  cardDesc: {
    fontSize: 12,
    color: '#331307',
    textAlign: 'center',
    marginTop: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    width: '80%',
    alignItems: 'center',
  },
  modalImage: {
    width: '100%',
    aspectRatio: 3 / 4,
    borderRadius: 10,
    marginBottom: 15,
    resizeMode: 'cover',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#331307',
    textAlign: 'center',
  },
  modalDesc: {
    fontSize: 14,
    color: '#331307',
    marginVertical: 10,
    textAlign: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: -14,
    right: -14,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 0,
    zIndex: 10,
    elevation: 6,
  },
  deleteButton: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DB3A34',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  deleteButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    marginLeft: 6,
  },
});
